import type { Metadata } from "next";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";

export const metadata: Metadata = {
  title: "How it works",
  description: "Learn how to use Pons Bot to manage a Robinhood Chain wallet, trade and swap tokens, claim creator fees, and launch on Pons V2.",
  alternates: { canonical: "/how-it-works" },
};

const steps = [
  { number: "01", title: "Post or open the terminal", body: "Mention @Ponsbotfamily in a new X post or reply, or connect your X account in the website terminal. Check balances, trade, transfer assets, burn tokens, or claim fees. Launches are submitted through X posts." },
  { number: "02", title: "Include the essentials", body: "Trades need an amount and asset. Token swaps need a dollar amount, source, and destination. Transfers also need a destination. Launches need a name and ticker; other launch details are optional." },
  { number: "03", title: "Review the result", body: "Pons Bot waits for confirmation and returns useful links. Multi-step actions produce one final result, and any partial completion is stated clearly." },
  { number: "04", title: "Return whenever you want", body: "Your wallet stays connected to your X account. Revisit its page or terminal to see holdings and recent actions." },
];

const commands = [
  { title: "Claim or view your wallet", body: "Ask for your wallet to create it or retrieve the same address later. The reply links to its public Pons Bot page, where anyone can view the address and holdings.", tips: ["No wallet address is required in your post.", "Your wallet remains associated with your X account.", "Never post a private key or recovery secret."], example: "@Ponsbotfamily what's my wallet?" },
  { title: "Check holdings", body: "Ask for your complete portfolio or name one asset to check a specific balance. Identify a token by ticker or contract address.", tips: ["Ask for holdings to see the full wallet.", "Name ETH, $PONSBOT, or a token contract for one balance.", "A leading $ on a ticker is optional."], example: "@Ponsbotfamily how much $PONSBOT do I have?" },
  { title: "Buy", body: "Include the token and an amount in USD, ETH, or its exact paired asset. If a USD or ETH purchase needs another pair, Pons Bot acquires that asset first and then completes the purchase with one final result.", tips: ["Use $25, 0.02 ETH, or a paired amount such as 5 MSFT.", "Paired-asset funding is handled automatically.", "You can also buy and send in one post."], example: "@Ponsbotfamily buy $25 of $PONSBOT" },
  { title: "Sell", body: "Name the token and specify an exact token amount, dollar value, percentage, half, or all. Pons Bot confirms the actual asset received.", tips: ["Use an amount such as 10 $PONSBOT.", "USD amounts, percentages, half, and all are supported.", "The token can be identified by contract address."], example: "@Ponsbotfamily sell half my $PONSBOT" },
  { title: "Swap one token for another", body: "Swap a dollar value of one token into another from an X post or terminal chat. Use the specific format below so the source and destination are unambiguous. Pons Bot uses a direct paired-asset route when available; otherwise it completes the confirmed route through ETH.", tips: ["Include the literal words swap, of, and for.", "Use tickers or complete contract addresses.", "Keep enough ETH available for every required transaction's gas."], example: "@Ponsbotfamily swap $25 of SNDK for $PONSBOT" },
  { title: "Send", body: "Send ETH or a supported token to an X user or wallet address. Include the amount, asset, and destination. A combined buy and send transfers only the tokens received from that purchase.", tips: ["Use an @username or complete 0x address.", "Exact amounts, percentages, half, and all are supported.", "Combined buy and send supports one token and recipient."], example: "@Ponsbotfamily send 10 $PONSBOT to @friend" },
  { title: "Burn", body: "Burning permanently sends tokens to the burn address. Include the token and amount, or explicitly request a combined buy and burn to destroy only the tokens received from that purchase.", tips: ["Burns are permanent.", "Combined buy and burn must contain both words buy and burn.", "Review the amount carefully."], example: "@Ponsbotfamily buy $25 of $PONSBOT and burn it" },
  { title: "Claim creator fees", body: "Pons V2 creator fees are credited in each launch's paired asset. Say “claim my fees” for the combined claim workflow, or name one launch. Pons Bot completes the required claim process and confirms the amount from the onchain event.", tips: ["Say claim my fees to claim everything supported by the combined workflow.", "Name $PONSBOT to claim only that launch's fees.", "Non-ETH-paired launches must be claimed individually."], example: "@Ponsbotfamily claim my fees for $PONSBOT" },
  { title: "Launch on Pons V2", body: "Verified X accounts can launch from an X post. A name and ticker are required. Artwork, description, website, X account, Telegram link, pair, and developer buy are optional. USD or ETH developer buys are automatically converted into a selected non-ETH pair first.", tips: ["Launches are submitted from X, not the terminal.", "Attach artwork to the launch post when desired.", "Website links are secured with HTTPS, and X handles or links are normalized to x.com/username.", "Use Telegram links in the format t.me/XXXXX; Pons Bot adds secure HTTPS automatically.", "Use dev buy $100 or an exact pair amount such as dev buy 2 MSFT."], example: "@Ponsbotfamily launch Pons Bot ticker $PONSBOT, website ponsbot.family, pair with MSFT" },
  { title: "Check pairing assets", body: "Ask Pons Bot for the current published pairing list, then include one supported asset in the launch post. Contract approval is checked only when that launch is requested.", tips: ["Available pairs: NVDA, SPCX, GOOGL, TSLA, RIVN, GME, AAPL, SPY, SNDK, AMD, AMZN, MSFT, META, CRCL, COIN, MU, PLTR, TTWO, COST, DJT, MSTR, QQQ, RDDT, USDG, and ETH.", "The list can change, so check again before launching.", "Use only one pair per launch."], example: "@Ponsbotfamily what assets can I pair with?" },
];

export default function HowItWorks() {
  return <main><SiteHeader /><section className="how-page">
    <div className="section-heading"><p className="eyebrow">How it works</p><h1>One X post.<br />A world of possibilities.</h1><p className="page-lede">Pons Bot gives you a Robinhood Chain wallet you can use from X or the website terminal. Check holdings, buy, sell, swap, send, burn, claim creator fees, or launch on Pons V2.</p></div>
    <div className="steps">{steps.map((step) => <article key={step.number}><span>{step.number}</span><h3>{step.title}</h3><p>{step.body}</p></article>)}</div>
    <section className="command-section"><p className="eyebrow">What you can do</p><h2>Everything you need, one request at a time.</h2><div className="command-grid">{commands.map((command) => <article key={command.title}><h3>{command.title}</h3><p>{command.body}</p><ul>{command.tips.map((tip) => <li key={tip}>{tip}</li>)}</ul><code>{command.example}</code></article>)}</div></section>
    <section className="launch-guide"><div><p className="eyebrow">Launch on Pons V2</p><h2>Start simple. Add the details that make it yours.</h2></div><div className="launch-detail-list"><p><strong>Account eligibility</strong><span>Your current X account must be verified.</span></p><p><strong>Required details</strong><span>Choose a token name and ticker, such as Pons Bot and $PONSBOT.</span></p><p><strong>Make it recognizable</strong><span>Artwork and a concise description are optional and can be included in the launch post.</span></p><p><strong>Connect your community</strong><span>Add an optional website, X account, and Telegram link in the format t.me/XXXXX.</span></p><p><strong>Choose the market</strong><span>Select a supported pair such as MSFT. A USD or ETH dev buy is converted into MSFT first; “dev buy 2 MSFT” spends an exact pair amount.</span></p></div></section>
    <div className="example-panel"><p className="eyebrow">Example posts</p><div><span>“What&apos;s my wallet?”</span><span>“How much $PONSBOT do I have?”</span><span>“Buy $25 of $PONSBOT”</span><span>“Swap $25 of SNDK for $PONSBOT”</span><span>“Buy $100 of $PONSBOT and send it to @friend”</span><span>“Sell half my $PONSBOT”</span><span>“Send 10 $PONSBOT to @friend”</span><span>“Burn 10 $PONSBOT”</span><span>“Claim my fees for $PONSBOT”</span><span>“Launch Pons Bot ticker $PONSBOT, website ponsbot.family, pair with MSFT”</span></div></div>
  </section><SiteFooter /></main>;
}
