import type { Metadata } from "next";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";
import { PUBLISHED_PAIR_LIST } from "@/lib/pair-catalog";

export const metadata: Metadata = {
  title: "How it works",
  description: "Learn how to use Pons Bot to manage a Robinhood Chain wallet, trade and swap tokens, manage liquidity, claim creator fees, and launch on Pons V2.",
  alternates: { canonical: "/how-it-works" },
};

const steps = [
  { number: "01", title: "Post or open the terminal", body: "Mention @Ponsbotfamily in a new X post or reply, or connect your X account in the website terminal. Check balances, trade, transfer assets, burn tokens, or claim fees. Launches are submitted through X posts." },
  { number: "02", title: "Include the essentials", body: "Trades need an amount and asset. Token swaps need a dollar amount, source, and destination. Transfers also need a destination. Launches need a name; include a ticker or Pons Bot will derive one. Other launch details are optional." },
  { number: "03", title: "Review the result", body: "Ordinary wallet commands execute directly and return the result with useful links. Liquidity creation presents a quote for confirmation first. Multi-step actions state clearly if only part of the request completed." },
  { number: "04", title: "Return whenever you want", body: "Your wallet stays connected to your X account. Revisit its page or terminal to see holdings and recent actions." },
];

const commands = [
  { title: "Claim or view your wallet", body: "Ask for your wallet to create it or retrieve the same address later. The reply links to its public Pons Bot page, where anyone can view the address and holdings.", tips: ["No wallet address is required in your post.", "Your wallet remains associated with your X account."], example: "@Ponsbotfamily what's my wallet?" },
  { title: "Check holdings", body: "Ask for your complete portfolio or name one asset to check a specific balance. Identify a token by ticker or contract address.", tips: ["Ask for holdings to see the full wallet.", "Name ETH, $PONSBOT, or a token contract for one balance.", "A leading $ on a ticker is optional."], example: "@Ponsbotfamily how much $PONSBOT do I have?" },
  { title: "Buy", body: "Include the token and an amount in USD, ETH, or its exact paired asset. If a USD or ETH purchase needs another pair, Pons Bot acquires that asset first and then completes the purchase with one final result.", tips: ["Use $25, 0.02 ETH, or a paired amount such as 5 MSFT.", "Paired-asset funding is handled automatically.", "You can also buy and send in one post."], example: "@Ponsbotfamily buy $25 of $PONSBOT" },
  { title: "Sell", body: "Name the token and specify an exact token amount, ETH value, dollar value, percentage, half, or all. Pons Bot confirms the actual asset received.", tips: ["Use an amount such as 10 $PONSBOT or sell 0.001 ETH of $PONSBOT.", "ETH and USD values, percentages, half, and all are supported.", "The token can be identified by contract address."], example: "@Ponsbotfamily sell half my $PONSBOT" },
  { title: "Swap one token for another", body: "Swap a dollar value of one token into another from an X post or terminal chat. Use the specific format below so the source and destination are unambiguous. Pons Bot uses a direct paired-asset route when available; otherwise it completes the confirmed route through ETH.", tips: ["Format your request like: swap $25 of ETH to USDG.", "Use tickers or complete contract addresses.", "Keep enough ETH available for every required transaction's gas."], example: "@Ponsbotfamily swap $25 of ETH to USDG" },
  { title: "Cross-chain and private swaps", body: "Send ETH from your Pons Bot wallet on Robinhood Chain and receive a supported asset at a wallet address on another network through Houdini Swap. X handles are not accepted as destinations. A valid X command begins processing immediately.", tips: ["Use a clear format such as: Send $25 to WALLET ADDRESS as ASSET on CHAIN.", "You can specify the source as USD or ETH. The source is always Robinhood Chain ETH from your Pons Bot wallet.", "For ETH destinations, name the network, such as ETH on Ethereum or ETH on Base.", "Add private or privately to request private routing.", "Pons Bot posts a submitted message with the estimated wait, followed by the final success or failure result."], example: "@Ponsbotfamily Private send $25 to WALLET ADDRESS as ASSET on CHAIN" },
  { title: "Send", body: "Send ETH or a supported token to an X user or wallet address. Include the amount, asset, and destination. A combined buy and send transfers only the tokens received from that purchase.", tips: ["Use an @username or complete 0x address.", "Exact amounts, percentages, half, and all are supported.", "Combined buy and send supports one token and recipient."], example: "@Ponsbotfamily send 10 $PONSBOT to @friend" },
  { title: "Burn", body: "Burning permanently sends tokens to the burn address. Include the token and amount, or explicitly request a combined buy and burn to destroy only the tokens received from that purchase.", tips: ["Burns are permanent.", "Combined buy and burn must contain both words buy and burn.", "Review the amount carefully."], example: "@Ponsbotfamily buy $25 of $PONSBOT and burn it" },
  { title: "Create and manage liquidity", body: "Create a position with Delta Liquidity from X or terminal chat. Pons Bot can compare live pools or guide you through custom ETH or USDG settings, then presents a quote before moving funds.", tips: ["Start with a ticker or contract address and a budget.", "Choose a ranked pool or say custom pool to select the version, fee, MCap range, shape, and bands.", "After opening, use the LP identifier to check the position, view its NFTs, collect LP fees, or withdraw it fully.", "Partial withdrawals, adding to an existing position, and automatic compounding are not available."], example: "@Ponsbotfamily create a $100 liquidity position for $PONSBOT" },
  { title: "Claim creator fees", body: "Pons Bot V2 claims and payouts run automatically. 95% goes to the creator, while 5% is used to buy and burn $PONSBOT. A claim request can trigger an eligible V2 cycle and also collect eligible legacy creator fees.", tips: ["Say claim my fees for the combined workflow.", "Name $PONSBOT to request one launch.", "The confirmed V2 amount is the creator payout after the buyback and burn."], example: "@Ponsbotfamily claim my fees for $PONSBOT" },
  { title: "Reassign creator fees", body: "From an X post, the current controller can transfer future creator-fee rights for a Pons Bot launch to another Pons Bot wallet, a wallet address, or the token’s holders. This command is not available in the website terminal.", tips: ["Use Reassign $TICKER fees to @user for an X account or wallet address.", "Use Reassign $TICKER fees to holders to enable holder fee sharing.", "After a wallet reassignment, the recipient controls future creator-fee changes.", "Fees already credited to the previous recipient remain claimable by that recipient."], example: "@Ponsbotfamily Reassign $PONSBOT fees to @user" },
  { title: "Upgrade creator fees", body: "The current fee-rights controller can upgrade an eligible legacy Pons Bot launch to Pons Bot V2 from an X post. The upgrade enables automatic claims and payouts: 95% goes to the creator, while 5% is used to buy and burn $PONSBOT.", tips: ["Use the exact command Upgrade $TICKER or replace the ticker with a complete contract address.", "Only the wallet that currently controls the creator-fee rights can upgrade the launch.", "Tokens already sharing fees with holders are not eligible.", "This command is not available in the website terminal."], example: "@Ponsbotfamily Upgrade $TICKER" },
  { title: "Launch on Pons V2", body: "Verified X accounts can launch from an X post that explicitly mentions @Ponsbotfamily. A name is required; include a ticker or Pons Bot will derive one. Artwork, description, website, X account, Telegram link, pair, and developer buy are optional. USD or ETH developer buys are automatically converted into a selected non-ETH pair first.", tips: ["Explicitly mention @Ponsbotfamily in the launch post and tell us the token name you want.", "Attach your artwork to the post, or launch without an image and add one later where supported.", "Add any optional details you want displayed, including a ticker, description, website, X account, or t.me/XXXXX Telegram link.", "Choose ETH or another supported pairing asset. Add dev buy $100, dev buy 0.02 ETH, or an exact paired amount such as dev buy 2 MSFT.", "To send creator fees to someone else, include assign fees to followed by their X handle or wallet address.", "To share creator fees with token holders, include the exact phrase holder fee sharing. Use only one creator-fee option per launch."], example: "@Ponsbotfamily launch Pons Bot ticker $PONSBOT, website ponsbot.family" },
  { title: "Check pairing assets", body: "Ask Pons Bot for the current published pairing list, then include one supported asset in the launch post. Contract approval is checked only when that launch is requested.", tips: [`Available pairs: ${PUBLISHED_PAIR_LIST}.`, "You can refer to HIMS as Hims or Hims & Hers, BB as BlackBerry, and GLD as Gold or SPDR Gold Trust.", "For cbBTC, you can also say BTC, Bitcoin, Coinbase Bitcoin, Coinbase Wrapped Bitcoin, or Wrapped Bitcoin.", "The list can change, so check again before launching.", "Use only one pair per launch."], example: "@Ponsbotfamily what assets can I pair with?" },
];

export default function HowItWorks() {
  return <main><SiteHeader /><section className="how-page">
    <div className="section-heading"><p className="eyebrow">How it works</p><h1>One X post.<br />A world of possibilities.</h1><p className="page-lede">Pons Bot gives you a Robinhood Chain wallet you can use from X or the website terminal. Check holdings, buy, sell, swap, send, burn, manage liquidity, claim creator fees, or launch on Pons V2.</p></div>
    <div className="steps">{steps.map((step) => <article key={step.number}><span>{step.number}</span><h3>{step.title}</h3><p>{step.body}</p></article>)}</div>
    <section className="command-section"><p className="eyebrow">What you can do</p><h2>Everything you need, one request at a time.</h2><div className="command-grid">{commands.map((command) => <article key={command.title}><h3>{command.title}</h3><p>{command.body}</p><ul>{command.tips.map((tip) => <li key={tip}>{tip}</li>)}</ul><code>{command.example}</code></article>)}</div></section>
    <section className="launch-guide"><div><p className="eyebrow">Launch on Pons V2</p><h2>Start simple. Add the details that make it yours.</h2></div><div className="launch-detail-list"><p><strong>Account eligibility</strong><span>Your current X account must be verified.</span></p><p><strong>Required details</strong><span>Choose a token name, such as Pons Bot. Include $PONSBOT as the ticker or let Pons Bot derive one from the name.</span></p><p><strong>Make it recognizable</strong><span>Artwork and a concise description are optional and can be included in the launch post.</span></p><p><strong>Connect your community</strong><span>Add an optional website, X account, and Telegram link in the format t.me/XXXXX.</span></p><p><strong>Choose the market</strong><span>Select a supported pair such as MSFT. A USD or ETH dev buy is converted into MSFT first; “dev buy 2 MSFT” spends an exact pair amount.</span></p></div></section>
    <div className="example-panel"><p className="eyebrow">Example posts</p><div><span>“What&apos;s my wallet?”</span><span>“How much $PONSBOT do I have?”</span><span>“Buy $25 of $PONSBOT”</span><span>“Swap $25 of SNDK for $PONSBOT”</span><span>“Private send $25 to WALLET ADDRESS as ASSET on CHAIN”</span><span>“Buy $100 of $PONSBOT and send it to @friend”</span><span>“Sell half my $PONSBOT”</span><span>“Send 10 $PONSBOT to @friend”</span><span>“Burn 10 $PONSBOT”</span><span>“Create a $100 liquidity position for $PONSBOT”</span><span>“Claim my fees for $PONSBOT”</span><span>“Upgrade $TICKER”</span><span>“Launch Pons Bot ticker $PONSBOT, website ponsbot.family”</span></div></div>
  </section><SiteFooter /></main>;
}
