import type { Metadata } from "next";
import { LegalDocument, type LegalSection } from "@/components/LegalDocument";

export const metadata: Metadata = { title: "Risk Disclaimer", description: "Important risks associated with wallets, tokens, swaps, launches, and liquidity positions on Pons Bot.", alternates: { canonical: "/risk" } };

const sections: LegalSection[] = [
  { title: "Read before using Pons Bot", paragraphs: ["Using wallets, tokens, blockchain networks, smart contracts, swaps, launches, burns, fee systems, and liquidity protocols involves significant risk. You may lose some or all assets involved. Only use Pons Bot if you understand and accept these risks."] },
  { title: "No financial advice or guarantees", paragraphs: ["Pons Bot provides software and information, not investment, financial, legal, or tax advice. Nothing displayed or communicated by Pons Bot is a recommendation, endorsement, promise of profit, or representation that a token, launch, trade, route, or liquidity position is suitable for you."] },
  { title: "Wallet and transaction risk", bullets: ["Blockchain transactions may be permanent and cannot generally be cancelled, reversed, or recovered.", "Sending assets to the wrong address or network may result in permanent loss.", "A compromised X account, device, session, or credential may permit unauthorized instructions.", "Gas prices, transaction ordering, failed transactions, and network congestion can change outcomes and costs."] },
  { title: "Token and market risk", bullets: ["Tokens can be highly volatile, illiquid, manipulated, duplicated, misleading, or worthless.", "Token creators and other users may act dishonestly or abandon a project.", "Displayed market data may be delayed, incomplete, estimated, or derived from thin liquidity.", "Purchases and sales may experience price impact, slippage, failed routing, or an inability to exit."] },
  { title: "Smart-contract and protocol risk", paragraphs: ["Smart contracts, bridges, routers, bonding curves, liquidity pools, wallets, RPC services, indexers, APIs, and other software may contain bugs, vulnerabilities, incompatible behavior, or outages. Protocol rules and deployed contracts may change independently of Pons Bot."] },
  { title: "Cross-chain and private swap risk", paragraphs: ["Cross-chain and privacy-oriented swaps rely on independent providers and multiple networks. Quotes may expire, completion can be delayed or fail, and received amounts can differ from estimates. Privacy-oriented routing does not guarantee complete anonymity or prevent public blockchain analysis."] },
  { title: "Liquidity-position risk", bullets: ["A position earns fees only while its liquidity is active for the relevant market price.", "Price movement can change the assets held by a position and may create impermanent loss or concentrated exposure.", "Pool volume and prior fee generation do not guarantee future earnings.", "Withdrawing, claiming, rebalancing, or converting assets may incur fees, price impact, delays, or failures."] },
  { title: "Launch and creator-fee risk", paragraphs: ["Launching a token creates public, persistent blockchain activity. A launch may fail or deploy with information that cannot be changed onchain. Creator fees and automated buyback-and-burn activity depend on trading, contracts, available routes, and network conditions and are not guaranteed."] },
  { title: "Regulatory and tax risk", paragraphs: ["Laws and regulatory treatment of digital assets vary and may change. Some features may not be lawful or available where you live. You are responsible for legal compliance and for determining any reporting or tax obligations."] },
  { title: "Independent services", paragraphs: ["Pons Bot is independent and is not operated or endorsed by Pons, Robinhood, Delta Liquidity, Houdini Swap, X, Coinbase, or other third-party providers. Links, integrations, and displayed data do not constitute an endorsement or warranty of those services."] },
  { title: "Contact", paragraphs: ["Questions about this Risk Disclaimer may be sent to ponsbot@ponsbot.family."] },
];

export default function RiskPage() { return <LegalDocument eyebrow="Pons Bot legal" title="Risk Disclaimer" summary="Important information about the risks of wallets, tokens, transactions, launches, swaps, and liquidity." effective="September 2, 2026" sections={sections} />; }
